# Generated by Django 3.0.6 on 2021-06-18 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_jobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserApply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(null=True, upload_to='')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Jobs')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.StudentUser')),
            ],
        ),
    ]
