# Generated by Django 3.0.6 on 2021-06-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_remove_userapply_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserApply',
        ),
    ]
